name: Deploy WBF python-server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: wbf-python-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push the  Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${REPO_NAME}:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.actor }}/${REPO_NAME}:latest